"""empty message

Revision ID: 2640b5a24351
Revises: 4e46d354a54e
Create Date: 2014-08-06 19:29:53.102000

"""

# revision identifiers, used by Alembic.
revision = '2640b5a24351'
down_revision = '4e46d354a54e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article')
    ### end Alembic commands ###
