"""empty message

Revision ID: 4e46d354a54e
Revises: None
Create Date: 2014-08-06 18:51:19.631000

"""

# revision identifiers, used by Alembic.
revision = '4e46d354a54e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
